GRANT
SELECT,
INSERT
,
UPDATE,
DELETE
ON ALL TABLES IN SCHEMA public TO lotusdata;
GRANT
SELECT
ON ALL TABLES IN SCHEMA public TO lotusreader;
GRANT
SELECT,
UPDATE
ON ALL SEQUENCES IN SCHEMA public TO lotusdata;
