
export INTERIM_PATH = ${DATA_PATH}/interim
export INTERIM_DB_PATH = ${INTERIM_PATH}/db
export EXTERNAL_PATH = ${DATA_PATH}/external
export EXTERNAL_DB_SOURCE_PATH = ${EXTERNAL_PATH}/dbSource
export EXTERNAL_TRANSLATION_SOURCE_PATH = ${EXTERNAL_PATH}/translationSource

ifeq (MODE,full)
    export INTERIM_TABLE_PATH = ${DATA_PATH}/interim/tables
else ifeq (MODE,min)
    export INTERIM_TABLE_PATH = ${DATA_PATH}/interim/tables_min
else
    export INTERIM_TABLE_PATH = ${DATA_PATH}/interim/tables_test
endif

ifeq (MODE,full)
    export INTERIM_DICTIONARY_PATH = ${INTERIM_PATH}/dictionaries
else ifeq (MODE,min)
    export INTERIM_DICTIONARY_PATH = ${INTERIM_PATH}/dictionaries_min
else
    export INTERIM_DICTIONARY_PATH = ${INTERIM_PATH}/dictionaries_test
endif

export INTERIM_TABLE_ORIGINAL_PATH = ${INTERIM_TABLE_PATH}/0_original
export INTERIM_TABLE_ORIGINAL_STRUCTURE_PATH = ${INTERIM_TABLE_ORIGINAL_PATH}/structure
export INTERIM_TABLE_ORIGINAL_ORGANISM_PATH = ${INTERIM_TABLE_ORIGINAL_PATH}/organism
export INTERIM_TABLE_ORIGINAL_REFERENCE_PATH = ${INTERIM_TABLE_ORIGINAL_PATH}/reference
export INTERIM_TABLE_TRANSLATED_PATH = ${INTERIM_TABLE_PATH}/1_translated
export INTERIM_TABLE_TRANSLATED_STRUCTURE_PATH = ${INTERIM_TABLE_TRANSLATED_PATH}/structure
export INTERIM_TABLE_TRANSLATED_ORGANISM_PATH = ${INTERIM_TABLE_TRANSLATED_PATH}/organism
export INTERIM_TABLE_TRANSLATED_REFERENCE_PATH = ${INTERIM_TABLE_TRANSLATED_PATH}/reference
export INTERIM_TABLE_CLEANED_PATH = ${INTERIM_TABLE_PATH}/2_cleaned
export INTERIM_TABLE_CLEANED_STRUCTURE_PATH = ${INTERIM_TABLE_CLEANED_PATH}/structure
export INTERIM_TABLE_CLEANED_ORGANISM_PATH = ${INTERIM_TABLE_CLEANED_PATH}/organism
export INTERIM_TABLE_CLEANED_REFERENCE_PATH = ${INTERIM_TABLE_CLEANED_PATH}/reference
export INTERIM_TABLE_CURATED_PATH = ${INTERIM_TABLE_PATH}/3_curated
export INTERIM_TABLE_ANALYSED_PATH = ${INTERIM_TABLE_PATH}/4_analysed

export SRC_GATHERING_PATH = ${SRC_PATH}/1_gathering
export SRC_GATHERING_DB_PATH = ${SRC_GATHERING_PATH}/db
export SRC_GATHERING_TRANSLATION_PATH = ${SRC_GATHERING_PATH}/translation

export SRC_CURATING_PATH = ${SRC_PATH}/2_curating
export SRC_CURATING_1_INTEGRATING_PATH = ${SRC_CURATING_PATH}/1_integrating
export SRC_CURATING_EDITING_PATH = ${SRC_CURATING_PATH}/2_editing
export SRC_CURATING_EDITING_STRUCTURE_PATH =  ${SRC_CURATING_EDITING_PATH}/structure
export SRC_CURATING_EDITING_STRUCTURE_SUBSCRIPTS_PATH =  ${SRC_CURATING_EDITING_STRUCTURE_PATH}/subscripts
export SRC_CURATING_EDITING_STRUCTURE_SUBSCRIPTS_TRANSLATING_PATH =  ${SRC_CURATING_EDITING_STRUCTURE_SUBSCRIPTS_PATH}/1_translating
export SRC_CURATING_EDITING_STRUCTURE_SUBSCRIPTS_INTEGRATING_PATH =  ${SRC_CURATING_EDITING_STRUCTURE_SUBSCRIPTS_PATH}/2_integrating
export SRC_CURATING_EDITING_STRUCTURE_SUBSCRIPTS_CLEANINGANDENRICHING_PATH =  ${SRC_CURATING_EDITING_STRUCTURE_SUBSCRIPTS_PATH}/3_cleaningAndEnriching
export SRC_CURATING_EDITING_STRUCTURE_SUBSCRIPTS_ENRICHING_PATH =  ${SRC_CURATING_EDITING_STRUCTURE_SUBSCRIPTS_PATH}/4_enriching
export SRC_CURATING_EDITING_ORGANISM_PATH =  ${SRC_CURATING_EDITING_PATH}/organism
export SRC_CURATING_EDITING_ORGANISM_SUBSCRIPTS_PATH =  ${SRC_CURATING_EDITING_ORGANISM_PATH}/subscripts
export SRC_CURATING_EDITING_ORGANISM_SUBSCRIPTS_PATH_KT = ${SRC_CURATING_EDITING_ORGANISM_SUBSCRIPTS_PATH}/2_translating_organism_kotlin
export SRC_CURATING_EDITING_REFERENCE_PATH =  ${SRC_CURATING_EDITING_PATH}/reference
export SRC_CURATING_EDITING_REFERENCE_SUBSCRIPTS_PATH =  ${SRC_CURATING_EDITING_REFERENCE_PATH}/subscripts
export SRC_CURATING_EDITING_REFERENCE_SUBSCRIPTS_TRANSLATING_PATH =  ${SRC_CURATING_EDITING_REFERENCE_SUBSCRIPTS_PATH}/1_translating
export SRC_CURATING_3_INTEGRATING_PATH = ${SRC_CURATING_PATH}/3_integrating

export SRC_ANALYSING_PATH = ${SRC_PATH}/3_analysing

export SRC_VISUALIZING_PATH = ${SRC_PATH}/4_visualizing