= The LOTUS Initiative

As the shorter READMEs are the best, we decided to give detailed documentation in our https://github.com/lotusnprod/lotus-processor/wiki[Wiki].

*LOTUS*, actually, represents the most exhaustive resource of documented structure-organism pairs.
Within the frame of current computational approaches in Natural Produts’s research and related fields, 
these documented structure-organism pairs should allow a more complete understanding of organisms and their chemistry.

== Data Availability Statements

The data used to support the findings of this study have been deposited on OSF https://osf.io/pmgux/[https://osf.io/pmgux/].
An snapshot of the repository at the time of publication is also available under the same link.

== Dataset list

All data used for this study is listed under xref:docs/dataset.csv[docs/dataset.csv]

== Contributing

Please read xref:CONTRIBUTING.md[contributing] for details on our code of conduct, and the process for submitting pull requests to us.

== Authors

- *Adriano Rutz* - _Initial work_ - https://github.com/Adafede[Adafede]
- *Pierre-Marie Allard* - _Investigator_ - https://github.com/oolonek[oolonek]
- *Jonathan Bisson* - _Hacker in Chief_ - https://github.com/bjonnh[bjonnh]

See also the list of https://github.com/lotusnprod/lotus-processor/-/project_members[contributors] who participated in this project.

== License

This project is licensed under the GNU GPLv3 license - see the xref:LICENSE.md[license file] for details
