== Getting started

=== Instructions

These instructions will get you a copy of the project up and running on your local machine for development and testing purposes.

==== Clone the repository

[source,console]
----
git clone git@gitlab.com:lotus7/lotus-processor.git
----

==== Having the data in a different place

If you want to have the data in a different place (for example for running a test), you can set the environment variable **DATA_PATH**.

==== Use docker to build

Install docker on your machine, make sure it is on your path then. ## WORKING ONLY ON LINUX FOR NOW

[source,console]
----
make docker-build
make docker-bash
----

This will bring you in a container that will already have all the dependencies installed so you can run your commands in it.

==== Additional MAKE Readme

If you want more informations regarding how to use MAKE, please have a look at xref:docs/makefile.adoc[the specific documentation]

==== Conda environement

A "loose" environment.yml file is created and should allow to recreate a working env from he project without beeing too restrictive on the versions to install.
Install it by running in the home directory.

environment_strict.yml is corresponds to the exact versions we used. 

[source,console]
----
conda env create -f environment.yml
bash environment_non_conda.sh
----

If your environement is not directly sources by your default bash run the following lines

[source,console]
----
source ~/anaconda3/etc/profile.d/conda.sh

conda activate lotus_env
----

==== Running the tests

This will get additional bins you need and run the whole pipeline with a small test table.

[source,console]
----
make MODE=test curating-and-analysing-and-visualizing ## creating results for a test file, should fail at the last visualization step.
make tests ## comparing if tests meet expctations ## should fail actually
----

Once we will be releasing not only the tests but also the min table (1000 entries), users will be able to run (not working now):

[source,console]
----
make MODE=min curating-and-analysing-and-visualizing
----