name: lotus-test

on:
  push:
    branches:
      - main
      - feature-ci-*
  pull_request:
    branches:
      - main
      - feature-ci-*
jobs:
  lotus-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '16'
          cache: 'gradle'      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install mamba
        run: |
          conda install mamba -n base -c conda-forge
      - name: Install dependencies
        run: |
          $CONDA/bin/mamba env update -f environment.yml -n lotus_env
      - name: Install non-conda dependencies
        env:
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          conda run -n lotus_env bash environment_non_conda.sh
          conda run -n lotus_env Rscript -e 'remotes::install_github("ropensci/rcrossref")'
      - name: Run minimal example processing
        run: |
          conda run -n lotus_env MODE=test make lotus-quick
      - name: Create and populate .Renviron file
        env:
          CROSSREF_EMAIL: ${{ secrets.CROSSREF_EMAIL }}
        run: |
          touch .Renviron
          echo crossref_email="$CROSSREF_EMAIL" >> .Renviron
      - name: Run manual entry mode
        run: |
          cd src
          conda run -n lotus_env Rscript 1_gathering/db/manual/standardizing.R ../data/example/manual_example.tsv 
          cd ..
          conda run -n lotus_env MODE=manual make manual-entry
     # - name: Run analyzing
     #   run: |
     #    conda run -n lotus_env MODE=test make analyzing
     # - name: Install visualizing conda dependencies
     #   run: |
     #    $CONDA/bin/conda env create -q --file environment_visualizing.yml
     # - name: Install visualizing non-conda dependencies
     #   run: |
     #     conda run -n lotus_visualizing_env bash environment_visualizing_non_conda.sh
     # - name: Run visualizing
     #   run: |
     #     conda run -n lotus_visualizing_env MODE=min make visualizing

jobs:
  lotus-macOS:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '16'
          cache: 'gradle'      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install mamba
        run: |
          conda install mamba -n base -c conda-forge
      - name: Install dependencies
        run: |
          $CONDA/bin/mamba env update -f environment.yml -n lotus_env
      - name: Install non-conda dependencies
        env:
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          conda run -n lotus_env bash environment_non_conda.sh
          conda run -n lotus_env Rscript -e 'remotes::install_github("ropensci/rcrossref")'
      - name: Run minimal example processing
        run: |
          conda run -n lotus_env MODE=test make lotus-quick
      - name: Create and populate .Renviron file
        env:
          CROSSREF_EMAIL: ${{ secrets.CROSSREF_EMAIL }}
        run: |
          touch .Renviron
          echo crossref_email="$CROSSREF_EMAIL" >> .Renviron
      - name: Run manual entry mode
        run: |
          cd src
          conda run -n lotus_env Rscript 1_gathering/db/manual/standardizing.R ../data/example/manual_example.tsv 
          cd ..
          conda run -n lotus_env MODE=manual make manual-entry
     # - name: Run analyzing
     #   run: |
     #    conda run -n lotus_env MODE=test make analyzing
     # - name: Install visualizing conda dependencies
     #   run: |
     #    $CONDA/bin/conda env create -q --file environment_visualizing.yml
     # - name: Install visualizing non-conda dependencies
     #   run: |
     #     conda run -n lotus_visualizing_env bash environment_visualizing_non_conda.sh
     # - name: Run visualizing
     #   run: |
     #     conda run -n lotus_visualizing_env MODE=min make visualizing
