name: lotus-test

on:
  push:
    branches:
      - main
      - feature-ci-*
  pull_request:
    branches:
      - main
      - feature-ci-*

jobs:
  lotus-test:
    name: tima-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '16'
          cache: 'gradle'      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - if: matrix.os == 'windows-latest'
        uses: Vampire/setup-wsl@v1.1.0
        with:
          additional-packages:
            curl
            gzip
            make
            unzip
            wget
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          mamba-version: "*"
          channels: conda-forge, bioconda, defaults
          channel-priority: true
          activate-environment: lotus_env
          environment-file: environment.yml
      - uses: s-weigand/setup-conda@v1
      - name: Create and populate .Renviron file
        env:
          CROSSREF_EMAIL: ${{ secrets.CROSSREF_EMAIL }}
        run: |
          touch .Renviron
          echo crossref_email="$CROSSREF_EMAIL" >> .Renviron
      - name: Run tests
        run: |
          bash tests/integration_test.sh