name: lotus-test

on:
  push:
    branches:
      - main
      - feature-ci-*
  pull_request:
    branches:
      - main
      - feature-ci-*

jobs:
  lotus-test:
    name: lotus-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          'ubuntu-latest', 
          # 'macos-latest'
          # 'windows-latest'
        ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: 'adopt-hotspot'
          java-version: '17'
          cache: 'gradle'      
      - uses: r-lib/actions/setup-r@d3c5be51b12e724e68f33216ca3c148b66d5f0b6
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476
        with:
          cache-downloads: true
          cache-environment: true
          environment-file: environment.yml
          create-args: >-
            python=3.11
      - name: Create and populate .Renviron file
        env:
          CROSSREF_EMAIL: ${{ secrets.CROSSREF_EMAIL }}
        run: |
          touch .Renviron
          echo crossref_email="$CROSSREF_EMAIL" >> .Renviron
      - name: Run tests
        env:
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        shell: bash -l {0}
        run: |
           bash tests/integration_test.sh
