on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '16'
          cache: 'gradle'      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install conda dependencies
        run: |
          $CONDA/bin/conda env create --file environment.yml
      - name: Install non-conda dependencies
        run: |
          conda run -n lotus_env bash environment_non_conda.sh
      - name: Run processing
        run: |
          conda run -n lotus_env MODE=min make lotus-quick
      - name: Run analyzing
        run: |
          conda run -n lotus_env MODE=min make analyzing
      - name: Install visualizing conda dependencies
        run: |
         $CONDA/bin/conda env create --file environment_visualizing.yml
      - name: Install visualizing non-conda dependencies
        run: |
          conda run -n lotus_visualizing_env bash environment_visualizing_non_conda.sh
      - name: Run visualizing
        run: |
          conda run -n lotus_visualizing_env MODE=min make visualizing
